#!/bin/bash
#
# Build docs and choke on gi-docgen warnings

DIR="${1:-_build}"
LOG="${DIR}/doc/doc-build.log"

meson compile -C "${DIR}" doc/phoc-doc |& tee "${LOG}"

if grep -vE  '('\
'register as boxed type or \(skip\)'\
'|symbol=.handle_.*Unknown namespace for symbol'\
'|wayland-server-core.h:.* syntax error, unexpected'\
'|argument pressed_keysyms: Unresolved type:'\
'|argument iterator: Unresolved type: .wlr_surface_iterator_func_t.'\
')' "${LOG}" | grep -i 'warning:'; then
    exit 1
fi
