#!/bin/bash

export LC_ALL=C

if [ -n "$1" ]; then
    cd "$1"
fi

if [ ! -d .git ]; then
  exit 0
fi

OUT=$(git grep -l '^[ ]*	' -- src/ tests/)
if [ -n "${OUT}" ]; then
    echo "ERROR: Tab indent in '${OUT}' detected." 1>&2
    exit 1
fi
